### ISSUE TITLE
Add features for patch generation via substitution with customized visualization

### ISSUE THREAD

**Issue by nealmcb** [isohedral/hatvalidate#3]
This validation code contains some useful underlying data structures which might be suitable for quickly generating patches of arbitrary size for analysis, visualization of patterns and arbitrary art.
I'm particularly interested in studying the interlocking tree structures of F metatiles in fylfots (along with a few other metatiles) that are visible in figure 2.12 of the original paper. 

 What would it take to add such features? Or would it be better to start from scratch?

I've run across some other apps or code bases exist in this space, implemented in other languages:

Javascript: [aperiodic monotile substitution / generation app](https://cs.uwaterloo.ca/~csk/hat/app.html)
with code at: [isohedral/hatviz: Simple P5js app for constructing aperiodic hat tilings](https://github.com/isohedral/hatviz)

Mathematica: [Hat tilings via HTPF equivalence \- Online Technical Discussion Groups—Wolfram Community](https://community.wolfram.com/groups/-/m/t/2858759)

**Comment by isohedral** [comment]
Yes, those are two good tools for generating patches of hats (the first is mine, the second is people at Wolfram). As long as you're focused purely on the hat tiling (and not tilings more generally), those tools are much more useful for generating large patches of tiles. 

This library was really designed for the sole purpose of supporting the validation component of our paper. Its contents could in principle be expanded to support many other features, but I wouldn't want to incorporate them here.

**Comment by nealmcb** [comment]
Fair enough. If I knew more Javascript or Mathematica, I'd build on those. Instead, I'll look for a better Python base, or just fork this for those purposes.
